### Monitors ###
source=./modules/monitors.conf

### Input Devices ###
source=./modules/input.conf

### Variables ###
source=./modules/variables.conf

### Basic Settings ###
source=./modules/tags.conf

### Layouts ###
source=./modules/layouts.conf

### Appearance ###
source=./modules/appearance.conf

### Window Rules ###
source=./modules/rules.conf

### Keybinding ###
source=./modules/binds.conf

### Autostart ###
exec-once=~/.config/mango/scripts/autostart.sh
