### Window Rules ###
windowrule=isfloating:1,appid:Rofi
windowrule=isfloating:1,appid:xfce-polkit

windowrule=isnoborder:1,appid:Rofi
windowrule=isnoanimation,1,appid:Rofi

layerrule=noanim:1,layer_name:rofi
layerrule=noanim:1,noblur:1,noshadow:1,layer_name:selection
