return {
  bg  = "#",
  fg  = "#",
  color1  = "#",
  color9  = "#",
  color2  = "#",
  color10 = "#",
  color3  = "#",
  color11 = "#",
  color4  = "#",
  color12 = "#",
  color5  = "#",
  color13 = "#",
  color6  = "#",
  color14 = "#",
  accent0 = "#",
  accent1 = "#",
}
