exec-once = signal-desktop
exec-once = vesktop
exec-once = flatpak run org.vinegarhq.Sober


input {
  kb_layout = pl
  kb_options = compose:caps
  numlock_by_default = true
  repeat_delay = 250
  repeat_rate = 35

  follow_mouse = 1
  off_window_axis_events = 2
  accel_profile = flat

  touchpad {
    natural_scroll = yes
    disable_while_typing = true
    clickfinger_behavior = true
    scroll_factor = 0.7
  }
}


windowrule = match:class ^(brave-browser)$, tag +browser
windowrule = match:class ^(app.zen_browser.zen)$, tag +browser

windowrule = match:class ^(org.kde.dolphin)$, tag +files
windowrule = match:class ^(org.gnome.World.PikaBackup)$, tag +files

windowrule = match:class ^([Ff]irefox)$, tag +projects
windowrule = match:class ^([Oo]bsidian)$, tag +projects
windowrule = match:class ^(LosslessCut)$, tag +projects

windowrule = match:class ^([Ss]ignal)$, tag +im
windowrule = match:class ^([Vv]esktop)$, tag +im

windowrule = match:class ^([Ss]team)$, tag +gamestore
windowrule = match:class ^(net.lutris.Lutris)$, tag +gamestore
windowrule = match:class ^([Hh]eroic)$, tag +gamestore
windowrule = match:class ^(com.usebottles.bottles)$, tag +gamestore
windowrule = match:class ^(org.prismlauncher.PrismLauncher)$, tag +gamestore

windowrule = match:class ^(gamescope)$, tag +games
windowrule = match:class ^(steam_app_\d+)$, tag +games
windowrule = match:class ^(steam_proton)$, tag +games

windowrule = match:class ^(virt-manager)$, tag +virt
windowrule = match:class ^(winboat)$, tag +virt


windowrule = match:tag browser*, workspace 1
windowrule = match:tag files*, workspace 2
windowrule = match:tag projects*, workspace 3
windowrule = match:tag im*, workspace 4 silent
windowrule = match:tag gamestore*, workspace 5
windowrule = match:tag games*, workspace 6
windowrule = match:class ^(com.obsproject.Studio)$, workspace 7
windowrule = match:class ^(LM Studio)$, workspace 8
windowrule = match:class ^(org.vinegarhq.Sober)$, workspace 9 silent
windowrule = match:tag virt*, workspace 10
