# This file sources other files in `overrides` folder

# Environment variables
source=overrides/env.conf

# Overrides
source=overrides/execs.conf
source=overrides/general.conf
source=overrides/rules.conf
source=overrides/keybinds.conf
