# This file sources other files in `overrides` folder
source=overrides/execs.conf
source=overrides/general.conf
source=overrides/rules.conf
source=overrides/keybinds.conf
source=overrides/master.conf
source=overrides/scrolling.conf
