# General
general {
  layout = scrolling
  }

scrolling {
  column_width = 0.5
  explicit_column_widths = 0.5, 1.0
  }

#animation = workspaces, 1, 7, menu_decel, slidevert

# Keybinds
unbind = Super, Period
bind = Super, comma,  layoutmsg, focus left
bind = Super, period, layoutmsg, focus right
bind = Super+Alt, comma, layoutmsg, colresize -conf
bind = Super+Alt, period, layoutmsg, colresize +conf
bind = Super+Shift, comma, layoutmsg, swapcol l
bind = Super+Shift, period, layoutmsg, swapcol r
