source = ~/.config/hypr/themes/dracula.conf

$font = Hack Mono Nerd Font

general {
  hide_cursor = false
}

background {
  monitor =
  path = screenshot
  blur_passes = 3
}

input-field {
 monitor =
 size = 15%, 5%
 outline_thickness = 1
 dots_size = 0.2
 dots_spacing = 0.2
 dots_center = true
 outer_color = rgba($fgAlpha00)
 inner_color =  rgba($fgAlpha1A)
 font_color = rgba($fgAlphaBF)
 fade_on_empty = false
 placeholder_text = 🔒 Enter Passsword
 hide_input = false
 position = 0, -64
 halign = center
 valign = center
}

# Clock
label {
 monitor =
 text = $TIME
 color = rgba($fgAlphaBF)
 font_size = 128
 font_family = $fg
 position = 0, 64
 halign = center
 valign = center
}
