[config]
version_check = false

[templates.discord]
input_path = '~/.config/matugen/templates/apps/Material-Discord.css'
output_path = '~/.config/vesktop/themes/Material-Discord.css'

[templates.obsidian]
input_path = '~/.config/matugen/templates/apps/Material-Obsidian.css'
output_path = '~/Dokumenty/obsidian/.obsidian/themes/Material-Obsidian.css'

[templates.zed]
input_path = '~/.config/matugen/templates/apps/Material-Zed.css'
output_path = '~/.config/zed/themes/Material-Zed.css'
