return {
  bgh = "#262626",
  bg = "{{colors.surface.default.hex}}",
  fg = "{{colors.on_surface.default.hex}}",
  red0 = "#ac8a8c",
  red1 = "#c49ea0",
  green0 = "#8aac8b",
  green1 = "#9ec49f",
  yellow0 = "#aca98a",
  yellow1 = "#c4c19e",
  blue0 = "{{colors.primary.default.hex}}",
  blue1 = "#a39ec4",
  magenta0 = "#ac8aac",
  magenta1 = "#c49ec4",
  cyan0 = "#8aacab",
  cyan1 = "#9ec3c4",
  accent0 = "{{colors.primary_container.default.hex}}",
  accent1 = "{{colors.primary_container.default.hex}}",
}
