return {
  bgh = "{{colors.outline_variant.default.hex}}",
  bg  = "{{colors.surface.default.hex}}",
  fg  = "{{colors.on_surface.default.hex}}",
  color1  = "{{colors.error.default.hex}}",
  color9  = "#c49ea0",
  color2  = "{{colors.on_surface.default.hex}}",
  color10 = "#9ec49f",
  color3  = "#aca98a",
  color11 = "#c4c19e",
  color4  = "{{colors.primary.default.hex}}",
  color12 = "#a39ec4",
  color5  = "{{colors.error.default.hex}}",
  color13 = "#c49ec4",
  color6  = "{{colors.on_surface.default.hex}}",
  color14 = "#9ec3c4",
  accent0 = "{{colors.outline.default.hex}}",
  accent1 = "{{colors.outline.default.hex}}",
}
