# Autostart

# Audio
exec-once = easyeffects --gapplication-service

# Bar
exec-once = waybar

# Clipboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = cliphist wipe

# Core
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = /usr/lib/polkit-kde-authentication-agent-1 || /usr/libexec/polkit-kde-authentication-agent-1  || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 || /usr/libexec/polkit-gnome-authentication-agent-1
exec-once = hypridle
exec-once = dbus-update-activation-environment --all
exec-once = sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = hyprpm reload

# Cursor
exec-once = hyprctl setcursor Bibata-Modern-Classic 24

# Input method
exec-once = fcitx5

# Instant messaging
exec-once = com.discordapp.Discord
exec-once = org.signal.Signal

# Notification Daemon
exec-once = swaync

# VPN
exec-once = mullvad-vpn

# Wallpaper
exec-once = hyprpaper
