$bg = rgb(282A36)
$bgAlpha = 282A36

$fg = rgb(F8F8F2)
$fgAlpha = F8F8F2

$selectedbg = rgb(44475A)
$selectedbgAlpha = 44475A

$black = rgb(6272A4)
$blackAlpha = 6272A4

$cyan = rgb(8BE9FD)
$cyanAlpha = 8BE9FD

$green = rgb(50FA7B)
$greenAlpha = 50FA7B

$orange = rgb(FFB86C)
$orangeAlpha = FFB86C

$pink = rgb(FF79C6)
$pinkAlpha = FF79C6

$purple = rgb(BD93F9)
$purpleAlpha = BD93F9

$red = rgb(FF5555)
$redAlpha = FF5555

$yellow = rgb(F1FA8C)
$yellowAlpha = F1FA8C
