# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Daemons
exec-once = cachy-update --tray
exec-once = pika-backup-monitor

# Apps
exec-once = [workspace 4 silent] signal-desktop
exec-once = [workspace 4 silent] vesktop
#exec-once = [workspace 9 silent] flatpak run org.vinegarhq.Sober
