# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Binds/

# Quickshell widgets
bindd = Super, Z, Toggle media mode, global, quickshell:mediaModeToggle

# Apps
unbind = Super, C
bind = Super, C, exec, zeditor # Code editor
unbind = Super, X
bind = Super, X, exec, obsidian # Text editor
unbind = Ctrl+Shift, Escape
bind = Ctrl+Shift, Escape, exec, kitty -1 fish -c btop # Task manager
