# Shell
bindd = Super, Z, Toggle media mode, global, quickshell:mediaModeToggle

# Master layout
unbind = Super, Period
bind = Super, comma,  layoutmsg, cyclenext
bind = Super, period, layoutmsg, cycleprev
bind = Super, Semicolon, layoutmsg, mfact -0.05
bind = Super, Apostrophe, layoutmsg, mfact +0.05
bind = Super+Shift, comma, layoutmsg, swapnext
bind = Super+Shift, period, layoutmsg, swapprev

# Scrolling layout
unbind = Super, Period
bind = Super, comma,  layoutmsg, focus left
bind = Super, period, layoutmsg, focus right
bind = Super, Semicolon, layoutmsg, colresize -conf
bind = Super, Apostrophe, layoutmsg, colresize +conf
bind = Super+Shift, comma, layoutmsg, swapcol l
bind = Super+Shift, period, layoutmsg, swapcol r

# Apps
unbind = Super, C
bind = Super, C, exec, zeditor # Code editor
unbind = Super, X
bind = Super, X, exec, obsidian --disable-gpu --enable-wayland-ime # Text editor
unbind = Ctrl+Shift, Escape
bind = Ctrl+Shift, Escape, exec, kitty -1 fish -c btop # Task manager
