# Relevant Hyprland wiki section: https://wiki.hypr.land/Configuring/Master-Layout/

master {
  mfact = 0.5
  new_status = slave
  }

# Keybinds
unbind = Super, Period
bind = Super, comma,  layoutmsg, cyclenext
bind = Super, period, layoutmsg, cycleprev
bind = Super, Semicolon, layoutmsg, mfact -0.05
bind = Super, Apostrophe, layoutmsg, mfact +0.05
bind = Super+Shift, comma, layoutmsg, swapnext
bind = Super+Shift, period, layoutmsg, swapprev
