# Relevant Hyprland wiki section:
# Window/layer rules: https://wiki.hypr.land/Configuring/Window-Rules/
# Workspace rules: https://wiki.hypr.land/Configuring/Workspace-Rules/

workspace = 9, layout:master
