# Transparency and blur
windowrule = opacity 0.9, match:class kitty

# Layout
workspace = 9, layout:master

# Apps
windowrule = match:class ^([Ss]ignal)$, workspace 4 silent
windowrule = match:class ^([Vv]esktop)$, workspace 4 silent
windowrule = match:class ^(org.vinegarhq.Sober)$, workspace 9 silent
