# Autostart

# Waybar
exec-once = waybar

# Wallpaper
exec-once = hyprpaper

# Idle Daemon
exec-once = hypridle

# Notification Daemon
exec-once = dunst

# Polkit
exec-once = systemctl --user start /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Clipboard
exec-once = wl-paste --watch cliphist store

# Cursor
exec-once= hyprctl setcursor WhiteSur-cursors 24

# rm Gamemode cache
exec-once = ~/.config/hypr/scripts/xdg.sh

# rm Gamemode cache
exec-once = ~/.config/hypr/scripts/gamemode.sh
