# Autostart

# Clipboard
exec-once = wl-paste --watch cliphist store

# Notification Daemon
exec-once = dunst

# rm Gamemode cache
exec-once = ~/.config/hypr/scripts/gamemode.sh

# Cursor
exec-once= hyprctl setcursor WhiteSur-cursors 24

# Idle Daemon
exec-once = hypridle

# Wallpaper
exec-once = hyprpaper

# Mullvad VPN
exec-once = mullvad-vpn-bin

# Polkit
exec-once = systemctl --user start /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Waybar
exec-once = waybar

# Run XDG
exec-once = ~/.config/hypr/scripts/xdg.sh
