# Window Rules

# Default
windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Pwvucontrol floating
windowrule = float, class:^(com.saivert.pwvucontrol)$
windowrule = size 700 600, class:^(com.saivertpwvucontrol)$
windowrule = center, class:^(com.saivert.pwvucontrol)$

# nwg-look floating
windowrule = float, class:^(nwg-look)$
windowrule = size 700 600, class:^(nwg-look)$
windowrule = move center, class:^(nwg-look)$

# Move to workspace
windowrule = workspace special silent, class:^(Mullvad VPN)$
windowrule = workspace 4 silent, class:^(com.discordapp.Discord)$

# Scratchpad "Look & Feel"
workspace = special:special, gapsout:32
