# Window Rules

windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

windowrule = float, class:^(com.saivert.pwvucontrol)$
windowrule = size 700 600, class:^(com.saivertpwvucontrol)$
windowrule = center, class:^(com.saivert.pwvucontrol)$

# nwg-look
windowrule = float, class:^(nwg-look)$
windowrule = size 700 600, class:^(nwg-look)$
windowrule = move center, class:^(nwg-look)$

windowrule = workspace special, class:^(Mullvad VPN)$

workspace = special:special, gapsout:32
