# Window Rules

# Disable blur for xwayland context menus
windowrule = noblur,class:^()$,title:^()$

# Move to workspace
windowrule = workspace special silent, class:^(Mullvad VPN)(.*)$
windowrule = workspace 4 silent, class:^(com.discordapp.Discord)(.*)$

# Scratchpad "Look & Feel"
workspace = special:special, gapsout:32

# Themes configuration floating
windowrule = tag +conf, class:^(nwg-look)(.*)$
windowrule = tag +conf, class:^(qt5ct)(.*)$
windowrule = tag +conf, class:^(qt6ct)(.*)$
windowrule = float, tag:conf
windowrule = size 45% 45%, tag:conf
windowrule = move center, tag:conf

# Pwvucontrol floating
windowrule = float, class:^(com.saivert.pwvucontrol)(.*)$
windowrule = size 45% 45%, class:^(com.saivertpwvucontrol)(.*)$
windowrule = move center, class:^(com.saivert.pwvucontrol)(.*)$

# Dialog windows floating
windowrule = float, class:^(xdg-desktop-portal-gtk)(.*)$
windowrule = size 45% 45%, class:^(xdg-desktop-portal-gtk)(.*)$
windowrule = move center, class:^(xdg-desktop-portal-gtk)(.*)$

# Games rules
windowrule = tag +games, class:^(gamescope)(.*)$
windowrule = tag +games, class:^(steam_app)(.*)$
windowrule = immediate, tag:games
windowrule = noblur, tag:games
windowrule = fullscreen, tag:games

# Layer rules
layerrule = blur, class:^([Rr]ofi)(.*)$
layerrule = ignorezero, class:^([Rr]ofi)(.*)$
layerrule = blur, notifications
layerrule = ignorezero, notifications
